# This file should be in the root of your project folder.

[build]
  # This is the directory that contains our frontend file (index.html).
  publish = "public"

# This section tells Netlify how to build your function.
[functions]
  # This ensures that Netlify installs the dependencies listed
  # in your function's own package.json file.
  node_bundler = "esbuild"
  directory = "netlify/functions"

# This rule makes our backend function available at a clean URL.
[[redirects]]
  # When the frontend calls any path starting with "/api/",
  from = "/api/*"
  
  # **FIX:** This path is now corrected to the standard pattern.
  # It correctly maps the public API path to the internal function path.
  to = "/.netlify/functions/server/api/:splat"
  
  # The HTTP status code for this internal rewrite. 200 means it's not a redirect.
  status = 200
